definitions:
  models.CreateUrlInput:
    properties:
      link:
        type: string
    required:
    - link
    type: object
  models.Url:
    properties:
      created_at:
        type: string
      id:
        type: integer
      original_url:
        type: string
      short_url:
        type: string
      updated_at:
        type: string
      view_count:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - application/json
      description: Create a new URL with a short URL
      operationId: create-url
      parameters:
      - description: URL input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateUrlInput'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/models.Url'
        "400":
          description: error
          schema:
            type: string
      summary: Create a new URL with a short URL
  /{short_url}:
    get:
      description: Redirect to the original URL from the short URL
      operationId: fetch-url
      parameters:
      - description: Short URL
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirect to the original URL
          schema:
            type: string
        "400":
          description: Record not found!
          schema:
            type: string
      summary: Redirect to the original URL from the short URL
swagger: "2.0"
